### ISSUE TITLE
Improve performance of LayoutLM and quality of input data

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/mozilla-sec-eia#23]
This is a running catalog of fixes that can be made to improve the performance of LayoutLM.

**Separate bounding boxes for _subsidiary-----location_ case**
<img width="248" alt="Screenshot 2024-04-29 at 3 13 05 PM" src="https://github.com/catalyst-cooperative/mozilla-sec-eia/assets/95320980/dc9e67bf-4188-474b-be0a-9c18768bd896">

Problem: The first word of the location gets grouped in the same bounding box as the last word in the company name because there is no white space separator, instead it's just a ----  
Solution: Break bounding boxes up in when there is a --- instead of just white space. 
Follow up: Fix the following labels in the training data

- [x] 1223037-2009q4-1223037-0001193125-09-249998

**Ex. 21 spans multiple pages**
Problem: It's quite common for an Ex. 21 table to span multiple pages in the PDF. These pages should be concatenated together and included in the "page" that is read in `extract_pdf_data_from_page`, or this workflow should be adapted so that multiple pages are parsed per doc.

Solution: 
* We already get PDFs of the Ex. 21 as multiple pages (if the Ex. 21 spans multiple pages)
* We can either treat these pages as separate docs or we can combine them into one "page" and process it all at once
* If we try combining the pages into one "page":
  * The biggest issue here is figuring out how the bounding box coordinates can be combined into one page
  * Seems like you might need to combine the pages into one PDF by adding heights and taking the maximum of widths
* If we treat each page separately:
  * Maybe there's no need to label multiple pages of Ex. 21, instead the labeled training data only has one page of the Ex. 21 PDF, and then during inference we treat each page separately and extract a separate dataframe for each page of the PDF, then finally combine dataframes based on CIK
  * This doesn't work if the second page requires schema or language context that's contained on the first page. But for the most part this doesn't seem to be the case. Example: In 4904-2009q1-4904-0000004904-09-000040 the second page contains footnotes that gives more context for ownership percentages.
  
Follow up: Fix the following docs
- [x] 61339-2017q1-61339-0001161728-17-000004

```[tasklist]
### Tasks
- [x] Separate bounding boxes between subsidiary and location when delimiter is --- not white space
- [x] Investigate what happens with image and JSON Label Studio input creation when Ex. 21 is multiple pages
- [ ] Decide what to do about nested subsidiaries
```

Possible way to combine PDF pages into one:
```
# Open the existing PDF
input_pdf = fitz.open("your_input_pdf.pdf")

# Create a new PDF document
output_pdf = fitz.open()

# Load the first and second pages
page1 = input_pdf.load_page(0)
page2 = input_pdf.load_page(1)

# Get the dimensions of the pages
width1, height1 = page1.rect.width, page1.rect.height
width2, height2 = page2.rect.width, page2.rect.height

# Determine the width and height for the new combined page
combined_width = max(width1, width2)
combined_height = height1 + height2

# Create a new page in the output PDF with the combined dimensions
combined_page = output_pdf.new_page(width=combined_width, height=combined_height)

# Define the matrices to position the pages in the new combined page
matrix1 = fitz.Matrix(1, 1)  # Identity matrix (no transformation)
matrix2 = fitz.Matrix(1, 1).preTranslate(0, height1)  # Translate the second page down by the height of the first page

# Insert the pages into the combined page
combined_page.show_pdf_page(page1.rect, input_pdf, 0, matrix=matrix1)
combined_page.show_pdf_page(page2.rect, input_pdf, 1, matrix=matrix2)

# Save the new combined PDF
output_pdf.save("combined_output_pdf.pdf")
```
