### ISSUE TITLE
Integrate experiment tracking into Ex. 21 Extraction module

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/mozilla-sec-eia#24]
We integrated a prototyped Ex. 21 extraction module that fine-tunes LayoutLM with the labeled data and then can perform inference to label entities in the Ex. 21 tables. Now, this module needs to be restructured with the MLFlow infrastructure so that we can track modeling experiments and more effectively track progress as we make iterations on the model.

```[tasklist]
### Tasks
- [x] Move the LayoutLM model out of notebook land and into the bones of a module
- [ ] Add experiment tracking locally with MLFlow
- [ ] https://github.com/catalyst-cooperative/mozilla-sec-eia/issues/29
```

Success criteria: 
* The preliminary module is improved with experiment tracking infrastructure from MLFlow and merged into `main`. 
* A basic set of metrics can be tracked between model iterations and these metrics are hosted by a remote server.

**Comment by jdangerx** [comment]
@katie-lamb how's this going? Is there a branch with your nascent module somewhere?

**Comment by katie-lamb** [comment]
@jdangerx we merged in a nascent module yesterday and then I handed it over to @zschira to work on restructuring it with MLflow experiment tracking. I'm spinning off the last task in this tasklist into a new issue that I'm working on now.

**Comment by jdangerx** [comment]
Let's split out the experiment tracking stuff so @zschira has a small contained issue to track that work.
