### ISSUE TITLE
Prototype module for inference and table extraction

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/mozilla-sec-eia#27]
LayoutLM conducts named entity recognition to label words with a particular entity type (subsidiary, location, etc). Now, we need to perform relation extraction to extract these entities into a database. A rule-based method seems to work fine as a rapid prototype. 

Rules:
* A group (row) should share the same y value (or be within a certain y threshold of each other if this is too restrictive)
* Only one subsidiary, location, own percentage per row

Then, a few regex replacement rules are used to remove extraneous special characters from ownership percentage.

This currently works in notebook land pretty effectively. I think the next steps are the following:

```[tasklist]
### Tasks
- [ ] Create an inference module that can perform inference with the fine-tuned models on unlabeled PDFs
- [ ] In the inference module build in a function to extract data from the doc into a dataframe
- [ ] Concatenate the extracted dataframe onto a larger dataframe of docs (with the idea that this can be written to an actual cloud based database)
```

**Success Criteria:**
* There is a module merged into `main` that takes the fine-tuned LayoutLM model, performs inference on a doc, and extracts the labeled entities into a structured table.
