### ISSUE TITLE
Add experiment tracking with a remote server

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/mozilla-sec-eia#29]
## Background
We're currently prototyping models for extracting exhibit 21 data. To enable collaboration and effective tracking of these models, we intend to use mlflow with a remote tracking server. This will allow the full team to save, version, and access fine-tuned models.

## TODO
- [x] Launch remote tracking server
- [x] Integrate tracking into fine-tuning script
- [ ] Provide helper functions to load fine-tuned model from remote storage.

## Success Criteria
This issue will be complete when there is a script that can fine-tune our extraction model, and save the results to remote storage + tooling to retrieve fine-tuned model for future use.
