### ISSUE TITLE
Log metrics with training data and validation dataframes

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/mozilla-sec-eia#34]
**Overview**

We need to develop metrics to validate the SEC basic information and Ex. 21 extraction models and verify the quality of the extracted data. These metrics can be integrated with MLFlow and tracked as we continue to develop the models. We want the metrics listed in the Metrics list below. Many of these can only be captured once we are able to run the model on all docs, but some of them we can start logging as soon as we have enough validation data.

**Success Criteria**

We have integrated tracking of above metrics into existing modules. This will be two PR's - the first is just to get a simple validation pipeline in place for metrics that we can start tracking without running on all docs. The second will be putting in more validation metrics once we can run on all docs.

```[tasklist]
### Metrics
- [x] Precision, recall, accuracy on labeled entity training data
- [x] Accuracy of table extraction model on transcribed dataframes
- [ ] Null value percentage in the columns of the SEC basic information
```

```[tasklist]
### Log Metrics with Training Data and Validation Data
- [ ] https://github.com/catalyst-cooperative/mozilla-sec-eia/issues/27
- [ ] https://github.com/catalyst-cooperative/mozilla-sec-eia/issues/39
- [x] Add validation checks using MLFlow in the table extraction module
```

```[tasklist]
### Tasks
```

**Comment by jdangerx** [comment]
@katie-lamb this is marked as in-review, is there a PR for this or is it also done in #43?

**Comment by katie-lamb** [comment]
@jdangerx I'm in the process of integrating a validation framework into #43 ! I was waiting for the basic 10K validation framework to get merged into main, and now will emulate what happens there in the Ex. 21 extraction.
