### ISSUE TITLE
Run extraction models on all documents

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/mozilla-sec-eia#40]
### Overview

#33 defines metrics we want to log when running exhibit 21/10k basic info extraction models on generic filings. Once we can log these metrics we should run the models on all docs and log the resulting metrics.

### Success Criteria

We have a pipeline that can run the current exhibit 21 and basic 10k extraction models on all archived docs, and compute metrics defined in #33.

```[tasklist]
### Tasks
- [x] Test running the pipeline on 100 docs on VM that is connected to GCS and do some memory profiling
- [x] Configure the VM to have GPU and test if we can run it - get baseline metrics for execution time
- [x] Add in memory profiling
- [x] Run on all docs
```
