### ISSUE TITLE
First pass at record linkage

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/mozilla-sec-eia#94]
# Overview

See [record linkage design doc](https://docs.google.com/document/d/1GPANDNf01Lc_oU8FSk3RUkByZta-bgb3dEUuvQrHRjk/edit?tab=t.0) for diagram and more notes.

We want to conduct record linkage between the SEC filers we've extracted and the companies (owner and operator utilities) that file with EIA (Form 860 and 861). There are a few more steps to make sure we have the correct data from both sides, and then we can do a proof of concept to make sure that splink can effectively connect SEC to EIA. 

# Success Criteria

* We have initial metrics on match performance from an unsupervised skeleton splink model
* We have metrics of performance on a validation set of manual matches 
* We've defined a threshold for match performance from the model metrics and validation set performance that we want to reach
* We've made a plan for reaching that threshold (if it isn't reached with skeleton model)

```[tasklist]
### Tasks
- [x] Check if there's utility address information reported in raw EIA 861 - see #96
- [x] Check that all owner companies are reported in the EIA 860 utilities table
- [x] Make a plan for reading in all SEC filer data
- [ ] Create a validation set of 50 manually mapped EIA utilities to SEC filers
- [x] Deduplicate SEC Ex. 21 subsidiary companies, assign a unique ID for all SEC companies
- [ ] #93
```

**Comment by katie-lamb** [comment]
The EIA 861 merger's table (`core_eia861__yearly_mergers`) has address information for the new parent company that can be joined on by `utility_id_eia`
